/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponseDto,
  HTTPValidationError,
  ProposalChatRequestDto,
  ProposalChatResponseDto,
  ProposalRejectRequestDto,
  ProposalResponseDto,
  TaskResponseDto
} from '../../model';

import { customInstance } from '../../../lib/axios-instance';




/**
 * @summary Chat
 */
export const chatApiV1TasksTaskIdChatPost = (
    taskId: number,
    proposalChatRequestDto: ProposalChatRequestDto,
 signal?: AbortSignal
) => {


      return customInstance<ProposalChatResponseDto>(
      {url: `/api/v1/tasks/${taskId}/chat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: proposalChatRequestDto, signal
    },
      );
    }



export const getChatApiV1TasksTaskIdChatPostMutationOptions = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chatApiV1TasksTaskIdChatPost>>, TError,{taskId: number;data: ProposalChatRequestDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof chatApiV1TasksTaskIdChatPost>>, TError,{taskId: number;data: ProposalChatRequestDto}, TContext> => {

const mutationKey = ['chatApiV1TasksTaskIdChatPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof chatApiV1TasksTaskIdChatPost>>, {taskId: number;data: ProposalChatRequestDto}> = (props) => {
          const {taskId,data} = props ?? {};

          return  chatApiV1TasksTaskIdChatPost(taskId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ChatApiV1TasksTaskIdChatPostMutationResult = NonNullable<Awaited<ReturnType<typeof chatApiV1TasksTaskIdChatPost>>>
    export type ChatApiV1TasksTaskIdChatPostMutationBody = ProposalChatRequestDto
    export type ChatApiV1TasksTaskIdChatPostMutationError = ErrorResponseDto | HTTPValidationError

    /**
 * @summary Chat
 */
export const useChatApiV1TasksTaskIdChatPost = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chatApiV1TasksTaskIdChatPost>>, TError,{taskId: number;data: ProposalChatRequestDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof chatApiV1TasksTaskIdChatPost>>,
        TError,
        {taskId: number;data: ProposalChatRequestDto},
        TContext
      > => {
      return useMutation(getChatApiV1TasksTaskIdChatPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Proposals
 */
export const getProposalsApiV1TasksTaskIdProposalsGet = (
    taskId: number,
 signal?: AbortSignal
) => {


      return customInstance<ProposalResponseDto[]>(
      {url: `/api/v1/tasks/${taskId}/proposals`, method: 'GET', signal
    },
      );
    }




export const getGetProposalsApiV1TasksTaskIdProposalsGetQueryKey = (taskId: number,) => {
    return [
    `/api/v1/tasks/${taskId}/proposals`
    ] as const;
    }


export const getGetProposalsApiV1TasksTaskIdProposalsGetQueryOptions = <TData = Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError = ErrorResponseDto | HTTPValidationError>(taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProposalsApiV1TasksTaskIdProposalsGetQueryKey(taskId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>> = ({ signal }) => getProposalsApiV1TasksTaskIdProposalsGet(taskId, signal);





   return  { queryKey, queryFn, enabled: !!(taskId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProposalsApiV1TasksTaskIdProposalsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>>
export type GetProposalsApiV1TasksTaskIdProposalsGetQueryError = ErrorResponseDto | HTTPValidationError


export function useGetProposalsApiV1TasksTaskIdProposalsGet<TData = Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError = ErrorResponseDto | HTTPValidationError>(
 taskId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>,
          TError,
          Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProposalsApiV1TasksTaskIdProposalsGet<TData = Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError = ErrorResponseDto | HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>,
          TError,
          Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProposalsApiV1TasksTaskIdProposalsGet<TData = Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError = ErrorResponseDto | HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Proposals
 */

export function useGetProposalsApiV1TasksTaskIdProposalsGet<TData = Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError = ErrorResponseDto | HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProposalsApiV1TasksTaskIdProposalsGetQueryOptions(taskId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Accept Proposal
 */
export const acceptProposalApiV1ProposalsProposalIdAcceptPost = (
    proposalId: number,
 signal?: AbortSignal
) => {


      return customInstance<TaskResponseDto>(
      {url: `/api/v1/proposals/${proposalId}/accept`, method: 'POST', signal
    },
      );
    }



export const getAcceptProposalApiV1ProposalsProposalIdAcceptPostMutationOptions = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acceptProposalApiV1ProposalsProposalIdAcceptPost>>, TError,{proposalId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof acceptProposalApiV1ProposalsProposalIdAcceptPost>>, TError,{proposalId: number}, TContext> => {

const mutationKey = ['acceptProposalApiV1ProposalsProposalIdAcceptPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof acceptProposalApiV1ProposalsProposalIdAcceptPost>>, {proposalId: number}> = (props) => {
          const {proposalId} = props ?? {};

          return  acceptProposalApiV1ProposalsProposalIdAcceptPost(proposalId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AcceptProposalApiV1ProposalsProposalIdAcceptPostMutationResult = NonNullable<Awaited<ReturnType<typeof acceptProposalApiV1ProposalsProposalIdAcceptPost>>>

    export type AcceptProposalApiV1ProposalsProposalIdAcceptPostMutationError = ErrorResponseDto | HTTPValidationError

    /**
 * @summary Accept Proposal
 */
export const useAcceptProposalApiV1ProposalsProposalIdAcceptPost = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acceptProposalApiV1ProposalsProposalIdAcceptPost>>, TError,{proposalId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof acceptProposalApiV1ProposalsProposalIdAcceptPost>>,
        TError,
        {proposalId: number},
        TContext
      > => {
      return useMutation(getAcceptProposalApiV1ProposalsProposalIdAcceptPostMutationOptions(options), queryClient);
    }
    /**
 * 거부 사유를 저장하고, 그 사유를 반영한 새 제안을 바로 돌려준다 (spec 51행).
 * @summary Reject Proposal
 */
export const rejectProposalApiV1ProposalsProposalIdRejectPost = (
    proposalId: number,
    proposalRejectRequestDto: ProposalRejectRequestDto,
 signal?: AbortSignal
) => {


      return customInstance<ProposalChatResponseDto>(
      {url: `/api/v1/proposals/${proposalId}/reject`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: proposalRejectRequestDto, signal
    },
      );
    }



export const getRejectProposalApiV1ProposalsProposalIdRejectPostMutationOptions = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectProposalApiV1ProposalsProposalIdRejectPost>>, TError,{proposalId: number;data: ProposalRejectRequestDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof rejectProposalApiV1ProposalsProposalIdRejectPost>>, TError,{proposalId: number;data: ProposalRejectRequestDto}, TContext> => {

const mutationKey = ['rejectProposalApiV1ProposalsProposalIdRejectPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rejectProposalApiV1ProposalsProposalIdRejectPost>>, {proposalId: number;data: ProposalRejectRequestDto}> = (props) => {
          const {proposalId,data} = props ?? {};

          return  rejectProposalApiV1ProposalsProposalIdRejectPost(proposalId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RejectProposalApiV1ProposalsProposalIdRejectPostMutationResult = NonNullable<Awaited<ReturnType<typeof rejectProposalApiV1ProposalsProposalIdRejectPost>>>
    export type RejectProposalApiV1ProposalsProposalIdRejectPostMutationBody = ProposalRejectRequestDto
    export type RejectProposalApiV1ProposalsProposalIdRejectPostMutationError = ErrorResponseDto | HTTPValidationError

    /**
 * @summary Reject Proposal
 */
export const useRejectProposalApiV1ProposalsProposalIdRejectPost = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectProposalApiV1ProposalsProposalIdRejectPost>>, TError,{proposalId: number;data: ProposalRejectRequestDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rejectProposalApiV1ProposalsProposalIdRejectPost>>,
        TError,
        {proposalId: number;data: ProposalRejectRequestDto},
        TContext
      > => {
      return useMutation(getRejectProposalApiV1ProposalsProposalIdRejectPostMutationOptions(options), queryClient);
    }
