/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChatRequestDto,
  ChatResponseDto,
  ErrorResponseDto,
  HTTPValidationError,
  ProposalAcceptResponseDto,
  ProposalRejectRequestDto,
  ProposalResponseDto
} from '../../model';

import { customInstance } from '../../../lib/axios-instance';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Chat
 */
export const chatApiV1TasksTaskIdChatPost = (
    taskId: number,
    chatRequestDto: ChatRequestDto,
 signal?: AbortSignal
) => {


      return customInstance<ChatResponseDto>(
      {url: `/api/v1/tasks/${taskId}/chat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: chatRequestDto, signal
    },
      );
    }




export const getChatApiV1TasksTaskIdChatPostMutationKey = () => ['chatApiV1TasksTaskIdChatPost'] as const;

export const getChatApiV1TasksTaskIdChatPostMutationOptions = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chatApiV1TasksTaskIdChatPost>>, TError,ChatApiV1TasksTaskIdChatPostMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof chatApiV1TasksTaskIdChatPost>>, TError,ChatApiV1TasksTaskIdChatPostMutationVariables, TContext> => {

const mutationKey = getChatApiV1TasksTaskIdChatPostMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof chatApiV1TasksTaskIdChatPost>>, ChatApiV1TasksTaskIdChatPostMutationVariables> = (props) => {
          const {taskId,data} = props ?? {};

          return  chatApiV1TasksTaskIdChatPost(taskId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ChatApiV1TasksTaskIdChatPostMutationResult = NonNullable<Awaited<ReturnType<typeof chatApiV1TasksTaskIdChatPost>>>
    export type ChatApiV1TasksTaskIdChatPostMutationBody = ChatRequestDto
    export type ChatApiV1TasksTaskIdChatPostMutationError = ErrorResponseDto | HTTPValidationError
    export type ChatApiV1TasksTaskIdChatPostMutationVariables = {taskId: number;data: ChatRequestDto}

    /**
 * @summary Chat
 */
export const useChatApiV1TasksTaskIdChatPost = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chatApiV1TasksTaskIdChatPost>>, TError,ChatApiV1TasksTaskIdChatPostMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof chatApiV1TasksTaskIdChatPost>>,
        TError,
        ChatApiV1TasksTaskIdChatPostMutationVariables,
        TContext
      > => {
      return useMutation(getChatApiV1TasksTaskIdChatPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Proposals
 */
export const getProposalsApiV1TasksTaskIdProposalsGet = (
    taskId: number,
 signal?: AbortSignal
) => {


      return customInstance<ProposalResponseDto[]>(
      {url: `/api/v1/tasks/${taskId}/proposals`, method: 'GET', signal
    },
      );
    }




export const getGetProposalsApiV1TasksTaskIdProposalsGetQueryKey = (taskId: number,) => {
    return [
    `/api/v1/tasks/${taskId}/proposals`
    ] as const;
    }


export const getGetProposalsApiV1TasksTaskIdProposalsGetQueryOptions = <TData = Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError = ErrorResponseDto | HTTPValidationError>(taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProposalsApiV1TasksTaskIdProposalsGetQueryKey(taskId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>> = ({ signal }) => getProposalsApiV1TasksTaskIdProposalsGet(taskId, signal);





   return  { queryKey, queryFn, enabled: taskId !== null && taskId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProposalsApiV1TasksTaskIdProposalsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>>
export type GetProposalsApiV1TasksTaskIdProposalsGetQueryError = ErrorResponseDto | HTTPValidationError


export function useGetProposalsApiV1TasksTaskIdProposalsGet<TData = Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError = ErrorResponseDto | HTTPValidationError>(
 taskId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>,
          TError,
          Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProposalsApiV1TasksTaskIdProposalsGet<TData = Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError = ErrorResponseDto | HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>,
          TError,
          Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProposalsApiV1TasksTaskIdProposalsGet<TData = Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError = ErrorResponseDto | HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Proposals
 */

export function useGetProposalsApiV1TasksTaskIdProposalsGet<TData = Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError = ErrorResponseDto | HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProposalsApiV1TasksTaskIdProposalsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProposalsApiV1TasksTaskIdProposalsGetQueryOptions(taskId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Accept Proposal
 */
export const acceptProposalApiV1ProposalsProposalIdAcceptPost = (
    proposalId: number,
 signal?: AbortSignal
) => {


      return customInstance<ProposalAcceptResponseDto>(
      {url: `/api/v1/proposals/${proposalId}/accept`, method: 'POST', signal
    },
      );
    }




export const getAcceptProposalApiV1ProposalsProposalIdAcceptPostMutationKey = () => ['acceptProposalApiV1ProposalsProposalIdAcceptPost'] as const;

export const getAcceptProposalApiV1ProposalsProposalIdAcceptPostMutationOptions = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acceptProposalApiV1ProposalsProposalIdAcceptPost>>, TError,AcceptProposalApiV1ProposalsProposalIdAcceptPostMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof acceptProposalApiV1ProposalsProposalIdAcceptPost>>, TError,AcceptProposalApiV1ProposalsProposalIdAcceptPostMutationVariables, TContext> => {

const mutationKey = getAcceptProposalApiV1ProposalsProposalIdAcceptPostMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof acceptProposalApiV1ProposalsProposalIdAcceptPost>>, AcceptProposalApiV1ProposalsProposalIdAcceptPostMutationVariables> = (props) => {
          const {proposalId} = props ?? {};

          return  acceptProposalApiV1ProposalsProposalIdAcceptPost(proposalId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AcceptProposalApiV1ProposalsProposalIdAcceptPostMutationResult = NonNullable<Awaited<ReturnType<typeof acceptProposalApiV1ProposalsProposalIdAcceptPost>>>

    export type AcceptProposalApiV1ProposalsProposalIdAcceptPostMutationError = ErrorResponseDto | HTTPValidationError
    export type AcceptProposalApiV1ProposalsProposalIdAcceptPostMutationVariables = {proposalId: number}

    /**
 * @summary Accept Proposal
 */
export const useAcceptProposalApiV1ProposalsProposalIdAcceptPost = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acceptProposalApiV1ProposalsProposalIdAcceptPost>>, TError,AcceptProposalApiV1ProposalsProposalIdAcceptPostMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof acceptProposalApiV1ProposalsProposalIdAcceptPost>>,
        TError,
        AcceptProposalApiV1ProposalsProposalIdAcceptPostMutationVariables,
        TContext
      > => {
      return useMutation(getAcceptProposalApiV1ProposalsProposalIdAcceptPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Close Proposal
 */
export const closeProposalApiV1ProposalsProposalIdClosePost = (
    proposalId: number,
 signal?: AbortSignal
) => {


      return customInstance<ProposalResponseDto>(
      {url: `/api/v1/proposals/${proposalId}/close`, method: 'POST', signal
    },
      );
    }




export const getCloseProposalApiV1ProposalsProposalIdClosePostMutationKey = () => ['closeProposalApiV1ProposalsProposalIdClosePost'] as const;

export const getCloseProposalApiV1ProposalsProposalIdClosePostMutationOptions = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof closeProposalApiV1ProposalsProposalIdClosePost>>, TError,CloseProposalApiV1ProposalsProposalIdClosePostMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof closeProposalApiV1ProposalsProposalIdClosePost>>, TError,CloseProposalApiV1ProposalsProposalIdClosePostMutationVariables, TContext> => {

const mutationKey = getCloseProposalApiV1ProposalsProposalIdClosePostMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof closeProposalApiV1ProposalsProposalIdClosePost>>, CloseProposalApiV1ProposalsProposalIdClosePostMutationVariables> = (props) => {
          const {proposalId} = props ?? {};

          return  closeProposalApiV1ProposalsProposalIdClosePost(proposalId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CloseProposalApiV1ProposalsProposalIdClosePostMutationResult = NonNullable<Awaited<ReturnType<typeof closeProposalApiV1ProposalsProposalIdClosePost>>>

    export type CloseProposalApiV1ProposalsProposalIdClosePostMutationError = ErrorResponseDto | HTTPValidationError
    export type CloseProposalApiV1ProposalsProposalIdClosePostMutationVariables = {proposalId: number}

    /**
 * @summary Close Proposal
 */
export const useCloseProposalApiV1ProposalsProposalIdClosePost = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof closeProposalApiV1ProposalsProposalIdClosePost>>, TError,CloseProposalApiV1ProposalsProposalIdClosePostMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof closeProposalApiV1ProposalsProposalIdClosePost>>,
        TError,
        CloseProposalApiV1ProposalsProposalIdClosePostMutationVariables,
        TContext
      > => {
      return useMutation(getCloseProposalApiV1ProposalsProposalIdClosePostMutationOptions(options), queryClient);
    }
    /**
 * @summary Reject Proposal
 */
export const rejectProposalApiV1ProposalsProposalIdRejectPost = (
    proposalId: number,
    proposalRejectRequestDto: ProposalRejectRequestDto,
 signal?: AbortSignal
) => {


      return customInstance<ChatResponseDto>(
      {url: `/api/v1/proposals/${proposalId}/reject`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: proposalRejectRequestDto, signal
    },
      );
    }




export const getRejectProposalApiV1ProposalsProposalIdRejectPostMutationKey = () => ['rejectProposalApiV1ProposalsProposalIdRejectPost'] as const;

export const getRejectProposalApiV1ProposalsProposalIdRejectPostMutationOptions = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectProposalApiV1ProposalsProposalIdRejectPost>>, TError,RejectProposalApiV1ProposalsProposalIdRejectPostMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof rejectProposalApiV1ProposalsProposalIdRejectPost>>, TError,RejectProposalApiV1ProposalsProposalIdRejectPostMutationVariables, TContext> => {

const mutationKey = getRejectProposalApiV1ProposalsProposalIdRejectPostMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rejectProposalApiV1ProposalsProposalIdRejectPost>>, RejectProposalApiV1ProposalsProposalIdRejectPostMutationVariables> = (props) => {
          const {proposalId,data} = props ?? {};

          return  rejectProposalApiV1ProposalsProposalIdRejectPost(proposalId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RejectProposalApiV1ProposalsProposalIdRejectPostMutationResult = NonNullable<Awaited<ReturnType<typeof rejectProposalApiV1ProposalsProposalIdRejectPost>>>
    export type RejectProposalApiV1ProposalsProposalIdRejectPostMutationBody = ProposalRejectRequestDto
    export type RejectProposalApiV1ProposalsProposalIdRejectPostMutationError = ErrorResponseDto | HTTPValidationError
    export type RejectProposalApiV1ProposalsProposalIdRejectPostMutationVariables = {proposalId: number;data: ProposalRejectRequestDto}

    /**
 * @summary Reject Proposal
 */
export const useRejectProposalApiV1ProposalsProposalIdRejectPost = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectProposalApiV1ProposalsProposalIdRejectPost>>, TError,RejectProposalApiV1ProposalsProposalIdRejectPostMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rejectProposalApiV1ProposalsProposalIdRejectPost>>,
        TError,
        RejectProposalApiV1ProposalsProposalIdRejectPostMutationVariables,
        TContext
      > => {
      return useMutation(getRejectProposalApiV1ProposalsProposalIdRejectPostMutationOptions(options), queryClient);
    }
