/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CodeQaChatRequestDto,
  ErrorResponseDto
} from '../../model';

import { customInstance } from '../../../lib/axios-instance';




/**
 * @summary Chat
 */
export const chatApiV1CodeQaChatPost = (
    codeQaChatRequestDto: CodeQaChatRequestDto,
 signal?: AbortSignal
) => {


      return customInstance<string>(
      {url: `/api/v1/code-qa/chat`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: codeQaChatRequestDto, signal
    },
      );
    }




export const getChatApiV1CodeQaChatPostMutationKey = () => ['chatApiV1CodeQaChatPost'] as const;

export const getChatApiV1CodeQaChatPostMutationOptions = <TError = void | ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chatApiV1CodeQaChatPost>>, TError,ChatApiV1CodeQaChatPostMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof chatApiV1CodeQaChatPost>>, TError,ChatApiV1CodeQaChatPostMutationVariables, TContext> => {

const mutationKey = getChatApiV1CodeQaChatPostMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof chatApiV1CodeQaChatPost>>, ChatApiV1CodeQaChatPostMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  chatApiV1CodeQaChatPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ChatApiV1CodeQaChatPostMutationResult = NonNullable<Awaited<ReturnType<typeof chatApiV1CodeQaChatPost>>>
    export type ChatApiV1CodeQaChatPostMutationBody = CodeQaChatRequestDto
    export type ChatApiV1CodeQaChatPostMutationError = void | ErrorResponseDto
    export type ChatApiV1CodeQaChatPostMutationVariables = {data: CodeQaChatRequestDto}

    /**
 * @summary Chat
 */
export const useChatApiV1CodeQaChatPost = <TError = void | ErrorResponseDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chatApiV1CodeQaChatPost>>, TError,ChatApiV1CodeQaChatPostMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof chatApiV1CodeQaChatPost>>,
        TError,
        ChatApiV1CodeQaChatPostMutationVariables,
        TContext
      > => {
      return useMutation(getChatApiV1CodeQaChatPostMutationOptions(options), queryClient);
    }
