/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HealthResponseDto
} from '../../model';

import { customInstance } from '../../../lib/axios-instance';




/**
 * @summary Liveness Check
 */
export const livenessCheckHealthLivenessGet = (

 signal?: AbortSignal
) => {


      return customInstance<HealthResponseDto>(
      {url: `/health/liveness`, method: 'GET', signal
    },
      );
    }




export const getLivenessCheckHealthLivenessGetQueryKey = () => {
    return [
    `/health/liveness`
    ] as const;
    }


export const getLivenessCheckHealthLivenessGetQueryOptions = <TData = Awaited<ReturnType<typeof livenessCheckHealthLivenessGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof livenessCheckHealthLivenessGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLivenessCheckHealthLivenessGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof livenessCheckHealthLivenessGet>>> = ({ signal }) => livenessCheckHealthLivenessGet(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof livenessCheckHealthLivenessGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LivenessCheckHealthLivenessGetQueryResult = NonNullable<Awaited<ReturnType<typeof livenessCheckHealthLivenessGet>>>
export type LivenessCheckHealthLivenessGetQueryError = unknown


export function useLivenessCheckHealthLivenessGet<TData = Awaited<ReturnType<typeof livenessCheckHealthLivenessGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof livenessCheckHealthLivenessGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof livenessCheckHealthLivenessGet>>,
          TError,
          Awaited<ReturnType<typeof livenessCheckHealthLivenessGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLivenessCheckHealthLivenessGet<TData = Awaited<ReturnType<typeof livenessCheckHealthLivenessGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof livenessCheckHealthLivenessGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof livenessCheckHealthLivenessGet>>,
          TError,
          Awaited<ReturnType<typeof livenessCheckHealthLivenessGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLivenessCheckHealthLivenessGet<TData = Awaited<ReturnType<typeof livenessCheckHealthLivenessGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof livenessCheckHealthLivenessGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Liveness Check
 */

export function useLivenessCheckHealthLivenessGet<TData = Awaited<ReturnType<typeof livenessCheckHealthLivenessGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof livenessCheckHealthLivenessGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLivenessCheckHealthLivenessGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Readiness Check
 */
export const readinessCheckHealthReadinessGet = (

 signal?: AbortSignal
) => {


      return customInstance<HealthResponseDto>(
      {url: `/health/readiness`, method: 'GET', signal
    },
      );
    }




export const getReadinessCheckHealthReadinessGetQueryKey = () => {
    return [
    `/health/readiness`
    ] as const;
    }


export const getReadinessCheckHealthReadinessGetQueryOptions = <TData = Awaited<ReturnType<typeof readinessCheckHealthReadinessGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readinessCheckHealthReadinessGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReadinessCheckHealthReadinessGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof readinessCheckHealthReadinessGet>>> = ({ signal }) => readinessCheckHealthReadinessGet(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof readinessCheckHealthReadinessGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReadinessCheckHealthReadinessGetQueryResult = NonNullable<Awaited<ReturnType<typeof readinessCheckHealthReadinessGet>>>
export type ReadinessCheckHealthReadinessGetQueryError = unknown


export function useReadinessCheckHealthReadinessGet<TData = Awaited<ReturnType<typeof readinessCheckHealthReadinessGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof readinessCheckHealthReadinessGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof readinessCheckHealthReadinessGet>>,
          TError,
          Awaited<ReturnType<typeof readinessCheckHealthReadinessGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadinessCheckHealthReadinessGet<TData = Awaited<ReturnType<typeof readinessCheckHealthReadinessGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readinessCheckHealthReadinessGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof readinessCheckHealthReadinessGet>>,
          TError,
          Awaited<ReturnType<typeof readinessCheckHealthReadinessGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReadinessCheckHealthReadinessGet<TData = Awaited<ReturnType<typeof readinessCheckHealthReadinessGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readinessCheckHealthReadinessGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Readiness Check
 */

export function useReadinessCheckHealthReadinessGet<TData = Awaited<ReturnType<typeof readinessCheckHealthReadinessGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof readinessCheckHealthReadinessGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReadinessCheckHealthReadinessGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






