/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ChatRequestDto {
  /**
     * Agent 에게 보내는 요청
     * @minLength 1
     */
  message: string;
}
