/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ProposalResponseDto } from './proposalResponseDto';
import type { ProposalToolEnum } from './proposalToolEnum';

export interface ChatResponseDto {
  tool: ProposalToolEnum;
  /** no_change 일 때 담당자에게 되묻는 말 */
  message?: string | null;
  proposal?: ProposalResponseDto | null;
  /** 현재 섹션 본문 → 제안 본문 unified diff */
  diff?: string | null;
}
