/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CodeQaMessageDtoRole = typeof CodeQaMessageDtoRole[keyof typeof CodeQaMessageDtoRole];


export const CodeQaMessageDtoRole = {
  user: 'user',
  assistant: 'assistant',
} as const;
