/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CodeQaMessageDtoRole } from './codeQaMessageDtoRole';

export interface CodeQaMessageDto {
  role: CodeQaMessageDtoRole;
  /** @minLength 1 */
  content: string;
}
