/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CodeQaMessageDto } from './codeQaMessageDto';

export interface CodeQaChatRequestDto {
  /**
     * 대화 이력 전체. 서버는 저장하지 않으며 마지막 항목이 이번 질문(user)이어야 한다
     * @minItems 1
     */
  messages: CodeQaMessageDto[];
  /** true 면 tool_result 이벤트에 도구 결과 전문(content)을 포함한다 */
  debug?: boolean;
}
