/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DiffLineDtoType } from './diffLineDtoType';
import type { DiffPartDto } from './diffPartDto';

/**
 * equal/insert/delete 는 text 를, changed 는 parts 를 쓴다.
 */
export interface DiffLineDto {
  type: DiffLineDtoType;
  text?: string;
  parts?: DiffPartDto[];
}
