/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type DiffLineDtoType = typeof DiffLineDtoType[keyof typeof DiffLineDtoType];


export const DiffLineDtoType = {
  equal: 'equal',
  insert: 'insert',
  delete: 'delete',
  changed: 'changed',
} as const;
