/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type DiffPartDtoOp = typeof DiffPartDtoOp[keyof typeof DiffPartDtoOp];


export const DiffPartDtoOp = {
  equal: 'equal',
  delete: 'delete',
  insert: 'insert',
} as const;
