/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ErrorResponseDto {
  status: number;
  statusText: string;
  message?: string | null;
  details?: unknown[] | null;
  timestamp: string;
}
