/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ProposalChatRequestDto {
  /**
     * Navi 에게 보낼 메시지
     * @minLength 1
     */
  message: string;
}
