/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ProposalResponseDto } from './proposalResponseDto';
import type { TaskSectionResponseDto } from './taskSectionResponseDto';

export interface ProposalAcceptResponseDto {
  proposal: ProposalResponseDto;
  /** 본문이 교체되고 버전이 오른 섹션 */
  section: TaskSectionResponseDto;
}
