/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ProposalRejectRequestDto {
  /**
     * 거부 사유: 재제안 프롬프트에 그대로 전달된다
     * @minLength 1
     */
  reason: string;
}
