/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ProposalResponseDtoToolInput } from './proposalResponseDtoToolInput';
import type { ProposalStatusEnum } from './proposalStatusEnum';
import type { ProposalToolEnum } from './proposalToolEnum';

export interface ProposalResponseDto {
  id: number;
  task_id: number;
  section_id: number;
  /** 제안 시점의 섹션 버전 */
  section_version: number;
  tool: ProposalToolEnum;
  tool_input: ProposalResponseDtoToolInput;
  status: ProposalStatusEnum;
  /** PENDING 인데 제안 이후 섹션이 바뀌어 수락할 수 없음 (수락 시 409) */
  is_stale: boolean;
  reject_reason: string | null;
  created_at: string;
  updated_at: string;
}
