/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ProposalToolEnum = typeof ProposalToolEnum[keyof typeof ProposalToolEnum];


export const ProposalToolEnum = {
  replace_section: 'replace_section',
  update_field: 'update_field',
  no_change: 'no_change',
} as const;
