/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ProposalStatusEnum } from './proposalStatusEnum';
import type { ProposalToolEnum } from './proposalToolEnum';

export interface ProposalResponseDto {
  id: number;
  task_id: number;
  tool: ProposalToolEnum;
  status: ProposalStatusEnum;
  task_version: number;
  reason: string | null;
  section: string | null;
  field: string | null;
  value: string | null;
  reject_reason: string | null;
  created_at: string;
}
