/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DiffLineDto } from './diffLineDto';
import type { ProposalResponseDto } from './proposalResponseDto';
import type { ProposalToolEnum } from './proposalToolEnum';

/**
 * no_change 는 제안 카드 없이 message 만 오고, 그 외에는 proposal 과 diff 가 온다.
 */
export interface ProposalChatResponseDto {
  tool: ProposalToolEnum;
  message?: string | null;
  proposal?: ProposalResponseDto | null;
  diff?: DiffLineDto[];
}
