/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ProposalRejectRequestDto {
  /**
     * 거부 사유 — 재제안에 그대로 반영된다
     * @minLength 1
     */
  reason: string;
}
