/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type TaskTypeEnum = typeof TaskTypeEnum[keyof typeof TaskTypeEnum];


export const TaskTypeEnum = {
  NEW_FEATURE: 'NEW_FEATURE',
  FEATURE_MODIFICATION: 'FEATURE_MODIFICATION',
  AUTOMATION_BATCH: 'AUTOMATION_BATCH',
  POLICY_CHANGE: 'POLICY_CHANGE',
} as const;
