/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TaskSectionTemplateDto } from './taskSectionTemplateDto';
import type { TaskTypeEnum } from './taskTypeEnum';

export interface TaskTypeTemplate {
  task_type: TaskTypeEnum;
  sections: TaskSectionTemplateDto[];
}
