/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface TaskSectionUpdateRequestDto {
  /** 섹션 내용 */
  body: string;
  /** 섹션 버전 */
  version: number;
}
