/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TaskTypeEnum } from './taskTypeEnum';

export interface TaskTypeTemplate {
  task_type: TaskTypeEnum;
  template: string;
}
