/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface TaskSectionTemplateDto {
  name: string;
  body: string;
  display_order: number;
  is_required: boolean;
}
