/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TaskStatusEnum } from './taskStatusEnum';
import type { TaskTypeEnum } from './taskTypeEnum';

export interface TaskCreateRequestDto {
  /** 태스크 제목 */
  title: string;
  /** 태스크 태그 */
  tags?: string | null;
  /** 태스크 타입 */
  task_type: TaskTypeEnum;
  /** 태스크 상태 */
  status: TaskStatusEnum;
  /** 노출순서: 0이  가장 높음 */
  display_order?: number;
  /** 우선순위: 0 ~ 4, 0이 가장 높음 */
  priority?: number;
}
