/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TaskStatusEnum } from './taskStatusEnum';

export interface TaskUpdateRequestDto {
  /** 태스크 제목 */
  title?: string | null;
  /** 태스크 내용 */
  content?: string | null;
  /** 태스크 태그 */
  tags?: string | null;
  /** 태스크 상태 */
  status?: TaskStatusEnum | null;
  /** 표시순서: 0이  가장 높음 */
  display_order?: number | null;
  /** 우선순위: 0 ~ 4, 0이 가장 높음 */
  priority?: number | null;
}
