/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface TaskSectionResponseDto {
  id: number;
  task_id: number;
  name: string;
  body: string;
  display_order: number;
  is_required: boolean;
  version: number;
  example_marker_count: number;
  created_at: string;
  updated_at: string;
}
