/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TaskStatusEnum } from './taskStatusEnum';
import type { TaskTypeEnum } from './taskTypeEnum';

export interface TaskResponseDto {
  id: number;
  title: string;
  content: string;
  tags: string | null;
  task_type: TaskTypeEnum;
  status: TaskStatusEnum;
  display_order: number;
  priority: number;
  version: number;
  is_archived: boolean;
  archived_at: string | null;
  created_at: string;
  updated_at: string;
}
