/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TaskStatusEnum } from './taskStatusEnum';

export interface TaskUpdateRequestDto {
  /** 태스크 제목 (null 불가) */
  title?: string | null;
  /** 태스크 태그 (null 이면 삭제) */
  tags?: string | null;
  /** 태스크 상태 (null 불가) */
  status?: TaskStatusEnum | null;
  /** 우선순위: 0 ~ 4, 0이 가장 높음 (null 불가) */
  priority?: number | null;
  /** 태스크 버전 */
  version: number;
}
