/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponseDto,
  HTTPValidationError,
  TaskCreateRequestDto,
  TaskReorderRequestDto,
  TaskResponseDto,
  TaskTypeTemplate,
  TaskUpdateRequestDto
} from '../../model';

import { customInstance } from '../../../lib/axios-instance';




/**
 * @summary Get Templates
 */
export const getTemplatesApiV1TasksTemplatesGet = (

 signal?: AbortSignal
) => {


      return customInstance<TaskTypeTemplate[]>(
      {url: `/api/v1/tasks/templates`, method: 'GET', signal
    },
      );
    }




export const getGetTemplatesApiV1TasksTemplatesGetQueryKey = () => {
    return [
    `/api/v1/tasks/templates`
    ] as const;
    }


export const getGetTemplatesApiV1TasksTemplatesGetQueryOptions = <TData = Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError = ErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTemplatesApiV1TasksTemplatesGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>> = ({ signal }) => getTemplatesApiV1TasksTemplatesGet(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTemplatesApiV1TasksTemplatesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>>
export type GetTemplatesApiV1TasksTemplatesGetQueryError = ErrorResponseDto


export function useGetTemplatesApiV1TasksTemplatesGet<TData = Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError = ErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>,
          TError,
          Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemplatesApiV1TasksTemplatesGet<TData = Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError = ErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>,
          TError,
          Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemplatesApiV1TasksTemplatesGet<TData = Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError = ErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Templates
 */

export function useGetTemplatesApiV1TasksTemplatesGet<TData = Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError = ErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTemplatesApiV1TasksTemplatesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Get Tasks
 */
export const getTasksApiV1TasksGet = (

 signal?: AbortSignal
) => {


      return customInstance<TaskResponseDto[]>(
      {url: `/api/v1/tasks`, method: 'GET', signal
    },
      );
    }




export const getGetTasksApiV1TasksGetQueryKey = () => {
    return [
    `/api/v1/tasks`
    ] as const;
    }


export const getGetTasksApiV1TasksGetQueryOptions = <TData = Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError = ErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTasksApiV1TasksGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTasksApiV1TasksGet>>> = ({ signal }) => getTasksApiV1TasksGet(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTasksApiV1TasksGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTasksApiV1TasksGet>>>
export type GetTasksApiV1TasksGetQueryError = ErrorResponseDto


export function useGetTasksApiV1TasksGet<TData = Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError = ErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTasksApiV1TasksGet>>,
          TError,
          Awaited<ReturnType<typeof getTasksApiV1TasksGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTasksApiV1TasksGet<TData = Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError = ErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTasksApiV1TasksGet>>,
          TError,
          Awaited<ReturnType<typeof getTasksApiV1TasksGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTasksApiV1TasksGet<TData = Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError = ErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Tasks
 */

export function useGetTasksApiV1TasksGet<TData = Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError = ErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTasksApiV1TasksGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Create Task
 */
export const createTaskApiV1TasksPost = (
    taskCreateRequestDto: TaskCreateRequestDto,
 signal?: AbortSignal
) => {


      return customInstance<TaskResponseDto>(
      {url: `/api/v1/tasks`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taskCreateRequestDto, signal
    },
      );
    }



export const getCreateTaskApiV1TasksPostMutationOptions = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTaskApiV1TasksPost>>, TError,{data: TaskCreateRequestDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createTaskApiV1TasksPost>>, TError,{data: TaskCreateRequestDto}, TContext> => {

const mutationKey = ['createTaskApiV1TasksPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTaskApiV1TasksPost>>, {data: TaskCreateRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  createTaskApiV1TasksPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateTaskApiV1TasksPostMutationResult = NonNullable<Awaited<ReturnType<typeof createTaskApiV1TasksPost>>>
    export type CreateTaskApiV1TasksPostMutationBody = TaskCreateRequestDto
    export type CreateTaskApiV1TasksPostMutationError = ErrorResponseDto | HTTPValidationError

    /**
 * @summary Create Task
 */
export const useCreateTaskApiV1TasksPost = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTaskApiV1TasksPost>>, TError,{data: TaskCreateRequestDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTaskApiV1TasksPost>>,
        TError,
        {data: TaskCreateRequestDto},
        TContext
      > => {
      return useMutation(getCreateTaskApiV1TasksPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Task
 */
export const getTaskApiV1TasksTaskIdGet = (
    taskId: number,
 signal?: AbortSignal
) => {


      return customInstance<TaskResponseDto>(
      {url: `/api/v1/tasks/${taskId}`, method: 'GET', signal
    },
      );
    }




export const getGetTaskApiV1TasksTaskIdGetQueryKey = (taskId: number,) => {
    return [
    `/api/v1/tasks/${taskId}`
    ] as const;
    }


export const getGetTaskApiV1TasksTaskIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError = ErrorResponseDto | HTTPValidationError>(taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTaskApiV1TasksTaskIdGetQueryKey(taskId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>> = ({ signal }) => getTaskApiV1TasksTaskIdGet(taskId, signal);





   return  { queryKey, queryFn, enabled: !!(taskId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTaskApiV1TasksTaskIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>>
export type GetTaskApiV1TasksTaskIdGetQueryError = ErrorResponseDto | HTTPValidationError


export function useGetTaskApiV1TasksTaskIdGet<TData = Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError = ErrorResponseDto | HTTPValidationError>(
 taskId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>,
          TError,
          Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaskApiV1TasksTaskIdGet<TData = Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError = ErrorResponseDto | HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>,
          TError,
          Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaskApiV1TasksTaskIdGet<TData = Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError = ErrorResponseDto | HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Task
 */

export function useGetTaskApiV1TasksTaskIdGet<TData = Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError = ErrorResponseDto | HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTaskApiV1TasksTaskIdGetQueryOptions(taskId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Update Task
 */
export const updateTaskApiV1TasksTaskIdPatch = (
    taskId: number,
    taskUpdateRequestDto: TaskUpdateRequestDto,
 signal?: AbortSignal
) => {


      return customInstance<TaskResponseDto>(
      {url: `/api/v1/tasks/${taskId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: taskUpdateRequestDto, signal
    },
      );
    }



export const getUpdateTaskApiV1TasksTaskIdPatchMutationOptions = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTaskApiV1TasksTaskIdPatch>>, TError,{taskId: number;data: TaskUpdateRequestDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTaskApiV1TasksTaskIdPatch>>, TError,{taskId: number;data: TaskUpdateRequestDto}, TContext> => {

const mutationKey = ['updateTaskApiV1TasksTaskIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTaskApiV1TasksTaskIdPatch>>, {taskId: number;data: TaskUpdateRequestDto}> = (props) => {
          const {taskId,data} = props ?? {};

          return  updateTaskApiV1TasksTaskIdPatch(taskId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTaskApiV1TasksTaskIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateTaskApiV1TasksTaskIdPatch>>>
    export type UpdateTaskApiV1TasksTaskIdPatchMutationBody = TaskUpdateRequestDto
    export type UpdateTaskApiV1TasksTaskIdPatchMutationError = ErrorResponseDto | HTTPValidationError

    /**
 * @summary Update Task
 */
export const useUpdateTaskApiV1TasksTaskIdPatch = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTaskApiV1TasksTaskIdPatch>>, TError,{taskId: number;data: TaskUpdateRequestDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTaskApiV1TasksTaskIdPatch>>,
        TError,
        {taskId: number;data: TaskUpdateRequestDto},
        TContext
      > => {
      return useMutation(getUpdateTaskApiV1TasksTaskIdPatchMutationOptions(options), queryClient);
    }
    /**
 * @summary Reorder Tasks
 */
export const reorderTasksApiV1TasksReorderPatch = (
    taskReorderRequestDto: TaskReorderRequestDto,
 signal?: AbortSignal
) => {


      return customInstance<TaskResponseDto[]>(
      {url: `/api/v1/tasks/reorder`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: taskReorderRequestDto, signal
    },
      );
    }



export const getReorderTasksApiV1TasksReorderPatchMutationOptions = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reorderTasksApiV1TasksReorderPatch>>, TError,{data: TaskReorderRequestDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof reorderTasksApiV1TasksReorderPatch>>, TError,{data: TaskReorderRequestDto}, TContext> => {

const mutationKey = ['reorderTasksApiV1TasksReorderPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reorderTasksApiV1TasksReorderPatch>>, {data: TaskReorderRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  reorderTasksApiV1TasksReorderPatch(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReorderTasksApiV1TasksReorderPatchMutationResult = NonNullable<Awaited<ReturnType<typeof reorderTasksApiV1TasksReorderPatch>>>
    export type ReorderTasksApiV1TasksReorderPatchMutationBody = TaskReorderRequestDto
    export type ReorderTasksApiV1TasksReorderPatchMutationError = ErrorResponseDto | HTTPValidationError

    /**
 * @summary Reorder Tasks
 */
export const useReorderTasksApiV1TasksReorderPatch = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reorderTasksApiV1TasksReorderPatch>>, TError,{data: TaskReorderRequestDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reorderTasksApiV1TasksReorderPatch>>,
        TError,
        {data: TaskReorderRequestDto},
        TContext
      > => {
      return useMutation(getReorderTasksApiV1TasksReorderPatchMutationOptions(options), queryClient);
    }
