/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponseDto,
  HTTPValidationError,
  SimpleTaskResponseDto,
  TaskCreateRequestDto,
  TaskReorderRequestDto,
  TaskResponseDto,
  TaskSectionResponseDto,
  TaskSectionUpdateRequestDto,
  TaskTypeTemplate,
  TaskUpdateRequestDto
} from '../../model';

import { customInstance } from '../../../lib/axios-instance';




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Get Templates
 */
export const getTemplatesApiV1TasksTemplatesGet = (

 signal?: AbortSignal
) => {


      return customInstance<TaskTypeTemplate[]>(
      {url: `/api/v1/tasks/templates`, method: 'GET', signal
    },
      );
    }




export const getGetTemplatesApiV1TasksTemplatesGetQueryKey = () => {
    return [
    `/api/v1/tasks/templates`
    ] as const;
    }


export const getGetTemplatesApiV1TasksTemplatesGetQueryOptions = <TData = Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError = ErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTemplatesApiV1TasksTemplatesGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>> = ({ signal }) => getTemplatesApiV1TasksTemplatesGet(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTemplatesApiV1TasksTemplatesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>>
export type GetTemplatesApiV1TasksTemplatesGetQueryError = ErrorResponseDto


export function useGetTemplatesApiV1TasksTemplatesGet<TData = Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError = ErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>,
          TError,
          Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemplatesApiV1TasksTemplatesGet<TData = Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError = ErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>,
          TError,
          Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemplatesApiV1TasksTemplatesGet<TData = Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError = ErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Templates
 */

export function useGetTemplatesApiV1TasksTemplatesGet<TData = Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError = ErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplatesApiV1TasksTemplatesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTemplatesApiV1TasksTemplatesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Get Tasks
 */
export const getTasksApiV1TasksGet = (

 signal?: AbortSignal
) => {


      return customInstance<TaskResponseDto[]>(
      {url: `/api/v1/tasks`, method: 'GET', signal
    },
      );
    }




export const getGetTasksApiV1TasksGetQueryKey = () => {
    return [
    `/api/v1/tasks`
    ] as const;
    }


export const getGetTasksApiV1TasksGetQueryOptions = <TData = Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError = ErrorResponseDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTasksApiV1TasksGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTasksApiV1TasksGet>>> = ({ signal }) => getTasksApiV1TasksGet(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTasksApiV1TasksGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTasksApiV1TasksGet>>>
export type GetTasksApiV1TasksGetQueryError = ErrorResponseDto


export function useGetTasksApiV1TasksGet<TData = Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError = ErrorResponseDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTasksApiV1TasksGet>>,
          TError,
          Awaited<ReturnType<typeof getTasksApiV1TasksGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTasksApiV1TasksGet<TData = Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError = ErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTasksApiV1TasksGet>>,
          TError,
          Awaited<ReturnType<typeof getTasksApiV1TasksGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTasksApiV1TasksGet<TData = Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError = ErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Tasks
 */

export function useGetTasksApiV1TasksGet<TData = Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError = ErrorResponseDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasksApiV1TasksGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTasksApiV1TasksGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Create Task
 */
export const createTaskApiV1TasksPost = (
    taskCreateRequestDto: TaskCreateRequestDto,
 signal?: AbortSignal
) => {


      return customInstance<TaskResponseDto>(
      {url: `/api/v1/tasks`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taskCreateRequestDto, signal
    },
      );
    }




export const getCreateTaskApiV1TasksPostMutationKey = () => ['createTaskApiV1TasksPost'] as const;

export const getCreateTaskApiV1TasksPostMutationOptions = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTaskApiV1TasksPost>>, TError,CreateTaskApiV1TasksPostMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createTaskApiV1TasksPost>>, TError,CreateTaskApiV1TasksPostMutationVariables, TContext> => {

const mutationKey = getCreateTaskApiV1TasksPostMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTaskApiV1TasksPost>>, CreateTaskApiV1TasksPostMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  createTaskApiV1TasksPost(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateTaskApiV1TasksPostMutationResult = NonNullable<Awaited<ReturnType<typeof createTaskApiV1TasksPost>>>
    export type CreateTaskApiV1TasksPostMutationBody = TaskCreateRequestDto
    export type CreateTaskApiV1TasksPostMutationError = ErrorResponseDto | HTTPValidationError
    export type CreateTaskApiV1TasksPostMutationVariables = {data: TaskCreateRequestDto}

    /**
 * @summary Create Task
 */
export const useCreateTaskApiV1TasksPost = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTaskApiV1TasksPost>>, TError,CreateTaskApiV1TasksPostMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTaskApiV1TasksPost>>,
        TError,
        CreateTaskApiV1TasksPostMutationVariables,
        TContext
      > => {
      return useMutation(getCreateTaskApiV1TasksPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Task
 */
export const getTaskApiV1TasksTaskIdGet = (
    taskId: number,
 signal?: AbortSignal
) => {


      return customInstance<TaskResponseDto>(
      {url: `/api/v1/tasks/${taskId}`, method: 'GET', signal
    },
      );
    }




export const getGetTaskApiV1TasksTaskIdGetQueryKey = (taskId: number,) => {
    return [
    `/api/v1/tasks/${taskId}`
    ] as const;
    }


export const getGetTaskApiV1TasksTaskIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError = ErrorResponseDto | HTTPValidationError>(taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTaskApiV1TasksTaskIdGetQueryKey(taskId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>> = ({ signal }) => getTaskApiV1TasksTaskIdGet(taskId, signal);





   return  { queryKey, queryFn, enabled: taskId !== null && taskId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTaskApiV1TasksTaskIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>>
export type GetTaskApiV1TasksTaskIdGetQueryError = ErrorResponseDto | HTTPValidationError


export function useGetTaskApiV1TasksTaskIdGet<TData = Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError = ErrorResponseDto | HTTPValidationError>(
 taskId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>,
          TError,
          Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaskApiV1TasksTaskIdGet<TData = Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError = ErrorResponseDto | HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>,
          TError,
          Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaskApiV1TasksTaskIdGet<TData = Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError = ErrorResponseDto | HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Task
 */

export function useGetTaskApiV1TasksTaskIdGet<TData = Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError = ErrorResponseDto | HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTaskApiV1TasksTaskIdGetQueryOptions(taskId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary Update Task
 */
export const updateTaskApiV1TasksTaskIdPatch = (
    taskId: number,
    taskUpdateRequestDto: TaskUpdateRequestDto,
 signal?: AbortSignal
) => {


      return customInstance<SimpleTaskResponseDto>(
      {url: `/api/v1/tasks/${taskId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: taskUpdateRequestDto, signal
    },
      );
    }




export const getUpdateTaskApiV1TasksTaskIdPatchMutationKey = () => ['updateTaskApiV1TasksTaskIdPatch'] as const;

export const getUpdateTaskApiV1TasksTaskIdPatchMutationOptions = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTaskApiV1TasksTaskIdPatch>>, TError,UpdateTaskApiV1TasksTaskIdPatchMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTaskApiV1TasksTaskIdPatch>>, TError,UpdateTaskApiV1TasksTaskIdPatchMutationVariables, TContext> => {

const mutationKey = getUpdateTaskApiV1TasksTaskIdPatchMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTaskApiV1TasksTaskIdPatch>>, UpdateTaskApiV1TasksTaskIdPatchMutationVariables> = (props) => {
          const {taskId,data} = props ?? {};

          return  updateTaskApiV1TasksTaskIdPatch(taskId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTaskApiV1TasksTaskIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateTaskApiV1TasksTaskIdPatch>>>
    export type UpdateTaskApiV1TasksTaskIdPatchMutationBody = TaskUpdateRequestDto
    export type UpdateTaskApiV1TasksTaskIdPatchMutationError = ErrorResponseDto | HTTPValidationError
    export type UpdateTaskApiV1TasksTaskIdPatchMutationVariables = {taskId: number;data: TaskUpdateRequestDto}

    /**
 * @summary Update Task
 */
export const useUpdateTaskApiV1TasksTaskIdPatch = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTaskApiV1TasksTaskIdPatch>>, TError,UpdateTaskApiV1TasksTaskIdPatchMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTaskApiV1TasksTaskIdPatch>>,
        TError,
        UpdateTaskApiV1TasksTaskIdPatchMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateTaskApiV1TasksTaskIdPatchMutationOptions(options), queryClient);
    }
    /**
 * @summary Reorder Tasks
 */
export const reorderTasksApiV1TasksReorderPatch = (
    taskReorderRequestDto: TaskReorderRequestDto,
 signal?: AbortSignal
) => {


      return customInstance<SimpleTaskResponseDto[]>(
      {url: `/api/v1/tasks/reorder`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: taskReorderRequestDto, signal
    },
      );
    }




export const getReorderTasksApiV1TasksReorderPatchMutationKey = () => ['reorderTasksApiV1TasksReorderPatch'] as const;

export const getReorderTasksApiV1TasksReorderPatchMutationOptions = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reorderTasksApiV1TasksReorderPatch>>, TError,ReorderTasksApiV1TasksReorderPatchMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof reorderTasksApiV1TasksReorderPatch>>, TError,ReorderTasksApiV1TasksReorderPatchMutationVariables, TContext> => {

const mutationKey = getReorderTasksApiV1TasksReorderPatchMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reorderTasksApiV1TasksReorderPatch>>, ReorderTasksApiV1TasksReorderPatchMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  reorderTasksApiV1TasksReorderPatch(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReorderTasksApiV1TasksReorderPatchMutationResult = NonNullable<Awaited<ReturnType<typeof reorderTasksApiV1TasksReorderPatch>>>
    export type ReorderTasksApiV1TasksReorderPatchMutationBody = TaskReorderRequestDto
    export type ReorderTasksApiV1TasksReorderPatchMutationError = ErrorResponseDto | HTTPValidationError
    export type ReorderTasksApiV1TasksReorderPatchMutationVariables = {data: TaskReorderRequestDto}

    /**
 * @summary Reorder Tasks
 */
export const useReorderTasksApiV1TasksReorderPatch = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reorderTasksApiV1TasksReorderPatch>>, TError,ReorderTasksApiV1TasksReorderPatchMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reorderTasksApiV1TasksReorderPatch>>,
        TError,
        ReorderTasksApiV1TasksReorderPatchMutationVariables,
        TContext
      > => {
      return useMutation(getReorderTasksApiV1TasksReorderPatchMutationOptions(options), queryClient);
    }
    /**
 * @summary Archive Task
 */
export const archiveTaskApiV1TasksTaskIdArchivePatch = (
    taskId: number,
 signal?: AbortSignal
) => {


      return customInstance<SimpleTaskResponseDto>(
      {url: `/api/v1/tasks/${taskId}/archive`, method: 'PATCH', signal
    },
      );
    }




export const getArchiveTaskApiV1TasksTaskIdArchivePatchMutationKey = () => ['archiveTaskApiV1TasksTaskIdArchivePatch'] as const;

export const getArchiveTaskApiV1TasksTaskIdArchivePatchMutationOptions = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof archiveTaskApiV1TasksTaskIdArchivePatch>>, TError,ArchiveTaskApiV1TasksTaskIdArchivePatchMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof archiveTaskApiV1TasksTaskIdArchivePatch>>, TError,ArchiveTaskApiV1TasksTaskIdArchivePatchMutationVariables, TContext> => {

const mutationKey = getArchiveTaskApiV1TasksTaskIdArchivePatchMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof archiveTaskApiV1TasksTaskIdArchivePatch>>, ArchiveTaskApiV1TasksTaskIdArchivePatchMutationVariables> = (props) => {
          const {taskId} = props ?? {};

          return  archiveTaskApiV1TasksTaskIdArchivePatch(taskId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ArchiveTaskApiV1TasksTaskIdArchivePatchMutationResult = NonNullable<Awaited<ReturnType<typeof archiveTaskApiV1TasksTaskIdArchivePatch>>>

    export type ArchiveTaskApiV1TasksTaskIdArchivePatchMutationError = ErrorResponseDto | HTTPValidationError
    export type ArchiveTaskApiV1TasksTaskIdArchivePatchMutationVariables = {taskId: number}

    /**
 * @summary Archive Task
 */
export const useArchiveTaskApiV1TasksTaskIdArchivePatch = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof archiveTaskApiV1TasksTaskIdArchivePatch>>, TError,ArchiveTaskApiV1TasksTaskIdArchivePatchMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof archiveTaskApiV1TasksTaskIdArchivePatch>>,
        TError,
        ArchiveTaskApiV1TasksTaskIdArchivePatchMutationVariables,
        TContext
      > => {
      return useMutation(getArchiveTaskApiV1TasksTaskIdArchivePatchMutationOptions(options), queryClient);
    }
    /**
 * @summary Unarchive Task
 */
export const unarchiveTaskApiV1TasksTaskIdUnarchivePatch = (
    taskId: number,
 signal?: AbortSignal
) => {


      return customInstance<SimpleTaskResponseDto>(
      {url: `/api/v1/tasks/${taskId}/unarchive`, method: 'PATCH', signal
    },
      );
    }




export const getUnarchiveTaskApiV1TasksTaskIdUnarchivePatchMutationKey = () => ['unarchiveTaskApiV1TasksTaskIdUnarchivePatch'] as const;

export const getUnarchiveTaskApiV1TasksTaskIdUnarchivePatchMutationOptions = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unarchiveTaskApiV1TasksTaskIdUnarchivePatch>>, TError,UnarchiveTaskApiV1TasksTaskIdUnarchivePatchMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof unarchiveTaskApiV1TasksTaskIdUnarchivePatch>>, TError,UnarchiveTaskApiV1TasksTaskIdUnarchivePatchMutationVariables, TContext> => {

const mutationKey = getUnarchiveTaskApiV1TasksTaskIdUnarchivePatchMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unarchiveTaskApiV1TasksTaskIdUnarchivePatch>>, UnarchiveTaskApiV1TasksTaskIdUnarchivePatchMutationVariables> = (props) => {
          const {taskId} = props ?? {};

          return  unarchiveTaskApiV1TasksTaskIdUnarchivePatch(taskId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UnarchiveTaskApiV1TasksTaskIdUnarchivePatchMutationResult = NonNullable<Awaited<ReturnType<typeof unarchiveTaskApiV1TasksTaskIdUnarchivePatch>>>

    export type UnarchiveTaskApiV1TasksTaskIdUnarchivePatchMutationError = ErrorResponseDto | HTTPValidationError
    export type UnarchiveTaskApiV1TasksTaskIdUnarchivePatchMutationVariables = {taskId: number}

    /**
 * @summary Unarchive Task
 */
export const useUnarchiveTaskApiV1TasksTaskIdUnarchivePatch = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unarchiveTaskApiV1TasksTaskIdUnarchivePatch>>, TError,UnarchiveTaskApiV1TasksTaskIdUnarchivePatchMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unarchiveTaskApiV1TasksTaskIdUnarchivePatch>>,
        TError,
        UnarchiveTaskApiV1TasksTaskIdUnarchivePatchMutationVariables,
        TContext
      > => {
      return useMutation(getUnarchiveTaskApiV1TasksTaskIdUnarchivePatchMutationOptions(options), queryClient);
    }
    /**
 * @summary Update Task Section
 */
export const updateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatch = (
    taskId: number,
    sectionId: number,
    taskSectionUpdateRequestDto: TaskSectionUpdateRequestDto,
 signal?: AbortSignal
) => {


      return customInstance<TaskSectionResponseDto>(
      {url: `/api/v1/tasks/${taskId}/sections/${sectionId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: taskSectionUpdateRequestDto, signal
    },
      );
    }




export const getUpdateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatchMutationKey = () => ['updateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatch'] as const;

export const getUpdateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatchMutationOptions = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatch>>, TError,UpdateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatchMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatch>>, TError,UpdateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatchMutationVariables, TContext> => {

const mutationKey = getUpdateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatchMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatch>>, UpdateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatchMutationVariables> = (props) => {
          const {taskId,sectionId,data} = props ?? {};

          return  updateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatch(taskId,sectionId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatch>>>
    export type UpdateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatchMutationBody = TaskSectionUpdateRequestDto
    export type UpdateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatchMutationError = ErrorResponseDto | HTTPValidationError
    export type UpdateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatchMutationVariables = {taskId: number;sectionId: number;data: TaskSectionUpdateRequestDto}

    /**
 * @summary Update Task Section
 */
export const useUpdateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatch = <TError = ErrorResponseDto | HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatch>>, TError,UpdateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatchMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatch>>,
        TError,
        UpdateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatchMutationVariables,
        TContext
      > => {
      return useMutation(getUpdateTaskSectionApiV1TasksTaskIdSectionsSectionIdPatchMutationOptions(options), queryClient);
    }
